//SUCCESS
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";

//ERROR
export const ERROR_CATEGORY_EXISTED = "ERROR_CATEGORY_EXISTED";
export const ERROR_CREATE_CATEGORY = "ERROR_CREATE_CATEGORY";
