// SUCCESS
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const GET_ORDER_HISTORY_SUCCESS = "GET_ORDER_HISTORY_SUCCESS";
// ERROR
export const ERROR_CREATE_ORDER = "ERROR_CREATE_ORDER";
export const ERROR_GET_ORDER_HISTORY = "ERROR_GET_ORDER_HISTORY";
