// SUCCESS
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_ITEM_SUCCESS = "GET_ORDER_ITEM_SUCCESS";
export const GET_ORDER_HISTORY_SUCCESS = "GET_ORDER_HISTORY_SUCCESS";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const CREAT_PAYMENT_URL_ZALOPAY_SUCCESS =
  "CREAT_PAYMENT_URL_ZALOPAY_SUCCESS";
export const QUERY_ORDER_STATUS_ZALOPAY_SUCCESS =
  "QUERY_ORDER_STATUS_ZALOPAY_SUCCESS";
// ERROR
export const ERROR_CREATE_ORDER = "ERROR_CREATE_ORDER";
export const ERROR_ORDER_NOT_FOUND = "ERROR_ORDER_NOT_FOUND";
export const ERROR_GET_ORDER = "ERROR_GET_ORDER";
export const ERROR_GET_ITEM_ORDER = "ERROR_GET_ITEM_ORDER";
export const ERROR_ORDER_ITEM_NOT_FOUND = "ERROR_ORDER_ITEM_NOT_FOUND";
export const ERROR_GET_ORDER_HISTORY = "ERROR_GET_ORDER_HISTORY";
export const ERROR_GET_ALL_ORDERS = "ERROR_GET_ALL_ORDERS";
export const ERROR_CREAT_PAYMENT_URL_ZALOPAY =
  "ERROR_CREAT_PAYMENT_URL_ZALOPAY";
export const ERROR_QUERY_ORDER_STATUS_ZALOPAY =
  "ERROR_QUERY_ORDER_STATUS_ZALOPAY";
