// SUCCESS
export const FIND_USER_BY_ID_SUCCESS = "FIND_USER_BY_ID_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

// ERROR
export const ERROR_GET_USER_BY_ID = "ERROR_GET_USER_BY_ID";
export const ERROR_CREATE_USER = "ERROR_CREATE_USER";
export const ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND";
