// SUCCESS
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const FIND_USER_BY_ID_SUCCESS = "FIND_USER_BY_ID_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const GET_MY_ADDRESSES_SUCCESS = "GET_MY_ADDRESSES_SUCCESS";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";
export const UPDATE_USER_SUCESS = "UPDATE_USER_SUCCESS";

// ERROR
export const LOGIN_FAIL = "LOGIN_FAIL";
export const ERROR_UPDATE_USER = "ERROR_UPDATE_USER";
export const ERROR_PASSWORD_NOT_MATCH = "ERROR_PASSWORD_NOT_MATCH";
export const ERROR_GET_USER_BY_ID = "ERROR_GET_USER_BY_ID";
export const ERROR_CREATE_USER = "ERROR_CREATE_USER";
export const ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND";
export const ERROR_GET_MY_ADDRESSES = "ERROR_GET_MY_ADDRESSES";
export const ERROR_GET_WISHLIST = "ERROR_GET_WISHLIST";
